<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SI1StSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $sis = [
            "Bingo (HK)",
            "Epochal Tech Holding Limited",
            "Futurus Innovations Limited",
            "Gosmart Limited",
            "Isaac IT Development Company",
            "Lloyds Oyman Technology Solutions Limited",
            "CTC Future Limited",
            "Varomatic Limited",
            "Benison IT Solutions Limited",
        ];

        $domains = [
            "bingo-hk-tech.com",
            "epochal-tech-hk.com",
            "futurustechhk.com",
            "gosmartltdhk.com",
            "iitdhk.com",
            "lotechsolutionshk.com",
            "ctcfuture.com",
            "varomatic-hk.com",
            "benison.tech",
        ];

        $businesses = [
            "祥發搬屋（香港）有限公司",
            "心願花藝設計",
            "洛瑤⼯程公司",
            "Dear. Gems",
            "百利⾏控股有限公司",
            "重慶華神麻辣火煱",
            "恒信紡織有限公司",
            "小林札幌拉麵",
            "J&J貿易公司",
            "Polly Law Beauty Centre",
            "VS Beauty & Slimming Limited",
            "Skyline Products Limited",
            "甜姨姨有限公司 ",
            "Nicole Beauty Limited",
            "IMT Group Limited",
            "滋味食堂",
            "華園甜品專家",
            "嘉和⽔電鎖類⼯程公司 ",
            "New Yan Restaurant Company Limited ",
            "唐⼈坊泰式海南雞餐廳",
            "中華世紀實業有限公司",
            "Wallen Jewellery Company Limited",
            "Jarvis Treatment Center Limited",
            "Absolute Vitality Limited",
            "潮眼鏡 ",
            "Renee Beauty Group Limited",
            "永逸燈飾",
            "⽝寶寶寵物美容店",
            "Mokchi Digital Limited ",
            "Manakamana Nepali Restaurant",
            "Salaam Namaste",
            "Genesis Dream Group Limited ",
            "Happy Yi Company Limited ",
            "佳輝飲食有限公司 ",
            "Genesis Dream Food And Beverage Limited",
            "⼭⽊傢俬有限公司 ",
            "晶藝軒精品公司",
            "聚靈軒⽔晶店 ",
            "AJ Fithub Limited",
            "新記鹵味 ",
            "Apyramidra Company Limited ",
            "海城中⻄葯⾏ ",
            "Mouse Workshop ",
            "柏奇國際集團貿易有限公司",
            "薈銓同沁教育有限公司",
        ];

        $emails = [
            "info@cheungfat.net",
            "wish.flower.info@gmail.com",
            "lokyiu.hk@gmail.com",
            "info.deargems@gmail.com",
            "sales@bethlehem-hk.com",
            "info.Hot.hotpot@gmail.com",
            "info@hstl-hk.com",
            "kobayashsappororamen@gmail.com",
            "cs.J.JTrading@gmail.com",
            "info.pollylawbeauty@gmail.com",
            "vsbeautyjd@gmail.com",
            "cs.skylineproduct@gmail.com",
            "Auntie.Sweet.info@gmail.com",
            "info.NicoleBeauty01@gmail.com",
            "cs.imt.group@gmail.com",
            "james.tastydiner@gmail.com",
            "Wahyuendessertspk@gmail.com",
            "info@guard-well.com",
            "restaurant.newyan@gmail.com",
            "tongyanfong@gmail.com",
            "info.chungwah@gmail.com",
            "info.Wallen.Jewellery@gmail.com",
            "jarvistcl007@gmail.com",
            "cs.avl.hk@gmail.com",
            "in.glasses@yahoo.com",
            "cs.renee.beauty@gmail.com ",
            "info.wingyatlighting@gmail.com",
            "info.cyclepet@gmail.com",
            "hk.mokchi@gmail.com",
            "cs.Manakamana@gmail.com",
            "order.SalaamNamaste@gmail.com",
            "info.genesisdream@gmail.com",
            "happyyi.ltd@gmail.com",
            "easythai.kaifai@gmail.com",
            "superdon.genesis@gmail.com",
            "admin2@shan-muk.com",
            "Artofcrystal.info@gmail.com",
            "c.h.crystal.shop@gmail.com",
            "Cs.ajfithub@gmail.com",
            "info.sunkee@gmail.com",
            "info.adprymidria@gmail.com",
            "info.hoishing@gmail.com",
            "Info.mouseworkshop@gmail.com",
            "info.hk.r.it@gmail.com",
            "cs.wellchamp.coheart@gmail.com",
        ];

        $contacts = [
            "61656161",
            "96787090",
            "97797832",
            "66446673",
            "24049081",
            "94873666",
            "39968100",
            "67016689",
            "97741717",
            "94399414",
            "63388655",
            "91931118",
            "25086962",
            "66881308",
            "66280115",
            "94655937",
            "68033296",
            "23313828",
            "39564838",
            "98723878",
            "23162388",
            "28902286",
            "31049283",
            "23078933",
            "67627444",
            "97048733",
            "24071683",
            "28121618",
            "61613628",
            "23852070",
            "24471401",
            "91857085",
            "67075828",
            "98777987",
            "61571922",
            "97504576",
            "96460706",
            "21211301",
            "60197911",
            "27898298",
            "39562369",
            "27554572",
            "29470737",
            "69006680",
            "53013943",
        ];

        $subdomains = [
            "cheungfat",
            "wishflowershop",
            "lokyiu",
            "deargems",
            "bethlehem",
            "chongqingwahsun",
            "hangseon",
            "kobayashiramen",
            "jnjtrading",
            "pollylawbeauty",
            "vsbeauty",
            "skylineproducts",
            "auntiesweet",
            "nicolebeauty",
            "imtgroup",
            "tastydiner",
            "wahyuendessert",
            "guardwell",
            "newyanrestaurant",
            "tongyanfong",
            "chungwahcentury",
            "wallenjewellery",
            "jarvistreatment",
            "avlhk",
            "inglasses",
            "reneebeauty",
            "wingyatlighting",
            "cyclepet",
            "mokchi",
            "manakamana",
            "salaamnamaste",
            "genesisdream",
            "happyyi",
            "kaifai",
            "superdongenesis",
            "shanmuk",
            "artofcrystal",
            "chcrystal",
            "ajfithub",
            "sunkee",
            "apyramidra",
            "hoishing",
            "mouseworkshop",
            "hkrinternationaltrading",
            "wellchamp",
        ];

        $siId = [
            "2",
            "2",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "4",
            "4",
            "4",
            "4",
            "4",
            "4",
            "4",
            "4",
            "5",
            "6",
            "6",
            "6",
            "6",
            "6",
            "6",
            "6",
            "7",
            "7",
            "7",
            "7",
            "7",
            "7",
            "7",
            "7",
            "7",
            "7",
            "8",
            "8",
            "8",
            "8",
            "8",
            "8",
            "9",
            "9",
            "10",
            "10",
        ];

        $accounts = [
            "jQWrfAdmin",
            "yrMchAdmin",
            "zBbJfAdmin",
            "fBOpZAdmin",
            "SXJZSAdmin",
            "emwPEAdmin",
            "ASxaeAdmin",
            "MiBuwAdmin",
            "mZvSxAdmin",
            "HSVmjAdmin",
            "aSaKEAdmin",
            "gEjoIAdmin",
            "yLfpvAdmin",
            "GCvkfAdmin",
            "wowNoAdmin",
            "axbMaAdmin",
            "FEetkAdmin",
            "gUeryAdmin",
            "GRIKKAdmin",
            "SzrSLAdmin",
            "nvGAGAdmin",
            "dsCagAdmin",
            "aDuaLAdmin",
            "BrpTEAdmin",
            "zqBSxAdmin",
            "wzDOcAdmin",
            "KAWSjAdmin",
            "QMYUjAdmin",
            "pLiXJAdmin",
            "XEjbAAdmin",
            "BHsmjAdmin",
            "fMirjAdmin",
            "OidmEAdmin",
            "gfdTwAdmin",
            "kPFuHAdmin",
            "MiGHcAdmin",
            "mZUroAdmin",
            "lDpjQAdmin",
            "CYSZkAdmin",
            "MZKqmAdmin",
            "LGGVBAdmin",
            "vCTMcAdmin",
            "uCRHvAdmin",
            "CzGtDAdmin",
            "bmewVAdmin",
        ];

        $passwords = [
            "7JGmDSAU",
            "GevbBnlz",
            "Lec0Ke38",
            "2e9kPs8f",
            "slT4Ub4G",
            "vjfkki3W",
            "RLD7ZnWL",
            "LOhytbXh",
            "OG7Q0Is7",
            "FUSUZbni",
            "bcXLZlkY",
            "z8XO3U55",
            "x7XwNzTm",
            "mR306aGm",
            "MNLgfZBJ",
            "5Zbh0Dfa",
            "ZKPDZQ9O",
            "C0YcWpoX",
            "8ykw1wtN",
            "gtUIsrYG",
            "8etRzm3H",
            "E1X3rMYv",
            "U8JC4u5V",
            "adJRVvT5",
            "QHvPRt75",
            "XGQvgFzP",
            "6jRTdp2O",
            "i8X1bNCi",
            "qLbmepIN",
            "Ol2u1htp",
            "gvQ0IGtn",
            "BK0oWsof",
            "An7LyNKD",
            "3Xn8Qhga",
            "S0LfResZ",
            "x1eCsKtk",
            "8Wnm9wXC",
            "xw43ZCbG",
            "z3MCu9GD",
            "aC2vMC4X",
            "Ecfy9S0D",
            "Fz2Lezev",
            "72Q1uLpm",
            "2TCnHiMu",
            "hFavDja6",
        ];

        $services = [
            ["全屋搬運服務", "傢私搬運服務",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約到店諮詢",],
            ["預約到店諮詢", "批發協商預約",],
            ["批發協商預約",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約（1-2人）", "預約（3-4人）",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約推廣療程試做",],
            ["預約推廣療程試做",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約推廣療程試做",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約到店諮詢",],
            ["預約到店諮詢",],
            ["預約到店諮詢", "預約推廣療程試做",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約到店諮詢", "預約維修",],
            ["預約推廣療程試做",],
            ["批發協商預約",],
            ["批發協商預約", "寵物美容（貓）預約", "寵物美容（狗）預約",],
            ["預約維修",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["批發協商預約",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約到店諮詢", "批發協商預約",],
            ["預約試堂",],
            ["預約（1-2人）", "預約（3-4人）", "預約（5-6人）",],
            ["預約到店諮詢", "批發協商預約",],
            ["批發協商預約", "中醫診症預約",],
            ["Design consulting",],
            ["預約到店諮詢", "批發合作討論預約", "貼膜",],
            ["預約試堂",],
        ];

//        $faker = Faker\Factory::create();

        foreach ($sis as $key => $value) {
            DB::table('solution_integrators')->insert([
                "title" => $value,
                "domain" => $domains[$key],
            ]);
        }

        foreach ($businesses as $key => $value) {
            $business_id = DB::table('businesses')->insertGetId([
                "title" => $value,
//                "address" => $faker->address,
                "phone" => $contacts[$key],
                'email' => $emails[$key],
                'solution_integrator_id' => $siId[$key],
                'subdomain' => $subdomains[$key],
            ]);

            DB::table('locations')->insert([
                ['title' => 'Warehouse', 'business_id' => $business_id],
                ['title' => 'Store', 'business_id' => $business_id],
            ]);

            foreach ($services[$key] as $service) {
                DB::table('services')->insert([
                    ['title' => $service, 'cost' => rand(100, 250), 'price' => rand(300, 400), 'business_id' => $business_id, 'division' => 30],
                ]);
            }
        }

        foreach ($accounts as $key => $value) {
            DB::table('users')->insert([
                "name" => $businesses[$key] . " Admin",
                "username" => $value,
                "password" => Hash::make($passwords[$key]),
                "business_id" => $key + 3,
            ]);
            User::find($key + 3)->assignRole('superAdmin');
        }

        function randomDate($start_date, $end_date)
        {
            $min = strtotime($start_date);
            $max = strtotime($end_date);

            $val = rand($min, $max);

            return [
                'date' => date('Y-m-d', $val),
                'time' => date('H:i', $val),
            ];
        }
    }
}
