<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    use \Backpack\CRUD\app\Models\Traits\CrudTrait;
    use HasFactory;

    protected $fillable = [
        'service_id',

        'customer_name',
        'customer_email',
        'customer_phone',
        'customer_password',
        'order_num',

        'booking_date',
        'booking_time',

        'business_id',

    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


        if (auth()->check()) {
            static::addGlobalScope('checkBusinessId', function (Builder $builder) {
                if (auth()->check()) {
//                    return $builder->where('business_id', auth()->user()['business_id']);
                    if (auth()->user()->isSuperAdmin == false) {
                        return $builder->where('business_id', backpack_user()->business_id);
                    }
                    return $builder;
                }
            });
        }
    }

    public function service()
    {
        return $this->belongsTo(Service::class);
    }

    public function business()
    {
        return $this->belongsTo(Business::class);
    }
}
