<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SupplierOrderItem extends Model
{
    use \Backpack\CRUD\app\Models\Traits\CrudTrait;
    use HasFactory;

    protected $fillable = [
        'supplier_order_id',
        'product_id',
        'quantity',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        if (auth()->check()) {
            static::addGlobalScope('checkBusinessId', function (Builder $builder) {
                if (auth()->check()) {
//                    return $builder->where('business_id', auth()->user()['business_id']);
                    if (auth()->user()->isSuperAdmin == false) {
                        return $builder->where('business_id', backpack_user()->business_id);
                    }
                    return $builder;
                }
            });
        }
    }

    public function supplierOrder()
    {
        return $this->belongsTo(SupplierOrder::class);

    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}
